language: java
jdk:
  - oraclejdk8
before_install:
  - openssl aes-256-cbc -K $encrypted_56555a7fdacc_key -iv $encrypted_56555a7fdacc_iv -in deployment.key.enc -out deployment.key -d
  - chmod +x ./gradlew
deploy:
  provider: script
  skip_cleanup: true
  script: /bin/sh ./scripts/deploy-jars.sh
  on:
    tags: true
