language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x ./gradlew
deploy:
  skip_cleanup: true
  script: ./gradlew bintrayUpload -PdeploymentVersion=${TRAVIS_TAG} -PvcsTag=${TRAVIS_TAG} --info
  on:
    tags: true
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
    
